# Generated by Django 4.2 on 2023-04-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.CharField(max_length=100, unique=True)),
                ('owner', models.CharField(max_length=200)),
                ('coach', models.CharField(max_length=100)),
                ('captain', models.CharField(max_length=100)),
                ('winning_seasons', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
